#include "utils.h"

#include "string.h"
#include "stdint.h"
#include "assert.h"

size_t __evil_write_literal(char *restrict *pbuf,
                            size_t *pbuf_size,
                            const char *str,
                            size_t str_size)
{
    size_t bytes_to_copy = str_size < *pbuf_size ? str_size : *pbuf_size;
    memcpy(*pbuf, str, bytes_to_copy);
    *pbuf += bytes_to_copy;
    *pbuf_size -= bytes_to_copy;
    return str_size;
}

static const char* const g_adjectives2_1[256] = {
    "Able",      "Active",    "Adored",    "Afraid",     "Ajar",
    "Alive",     "Amused",    "Ancient",   "Anguished",  "Anxious",
    "Arctic",    "Assured",   "Aware",     "Awful",      "Barren",
    "Beloved",   "Bitter",    "Blissful",  "Bogus",      "Bony",
    "Bossy",     "Brilliant", "Bubbly",    "Buoyant",    "Busy",
    "Candid",    "Carefree",  "Cautious",  "Cheerful",   "Chilly",
    "Clever",    "Clueless",  "Cluttered", "Complete",   "Composed",
    "Conscious", "Corny",     "Crafty",    "Creepy",     "Crowded",
    "Crushing",  "Cultured",  "Damaged",   "Daring",     "Dearest",
    "Delayed",   "Detailed",  "Direct",    "Discrete",   "Dismal",
    "Distant",   "Doting",    "Downright", "Drafty",     "Dreary",
    "Dual",      "Early",     "Easy",      "Enraged",    "Esteemed",
    "Evil",      "Failing",   "Famous",    "Fatal",      "Fearless",
    "Feline",    "Fickle",    "Finished",  "Flaky",      "Flawless",
    "Flippant",  "Fluid",     "Focused",   "Formal",     "Fragrant",
    "Friendly",  "Frigid",    "Frosty",    "Frugal",     "Fussy",
    "Gentle",    "Giddy",     "Giving",    "Gleaming",   "Gloomy",
    "Golden",    "Graceful",  "Greedy",    "Gripping",   "Grouchy",
    "Growing",   "Grubby",    "Guilty",    "Handsome",   "Happy",
    "Harmless",  "Hateful",   "Healthy",   "Hearty",     "Hefty",
    "Helpless",  "Homely",    "Honored",   "Humble",     "Hungry",
    "Husky",     "Ideal",     "Immense",   "Intent",     "Jaded",
    "Jealous",   "Joyful",    "Juicy",     "Jumpy",      "Kindly",
    "Knotty",    "Kooky",     "Lanky",     "Lavish",     "Lazy",
    "Leafy",     "Limping",   "Little",    "Livid",      "Lonely",
    "Lovely",    "Loyal",     "Lustrous",  "Mammoth",    "Massive",
    "Mealy",     "Meaty",     "Merry",     "Milky",      "Minor",
    "Modest",    "Monthly",   "Muddy",     "Mundane",    "Mushy",
    "Muted",     "Narrow",    "Naughty",   "Nervous",    "Nippy",
    "Normal",    "Noxious",   "Obese",     "Oblong",     "Offbeat",
    "Only",      "Other",     "Oval",      "Partial",    "Peaceful",
    "Perfumed",  "Pesky",     "Phony",     "Plaintive",  "Playful",
    "Pleasing",  "Pointless", "Portly",    "Precious",   "Pretty",
    "Prickly",   "Profuse",   "Prudent",   "Puny",       "Pushy",
    "Puzzled",   "Quiet",     "Ragged",    "Ready",      "Reckless",
    "Relieved",  "Rigid",     "Robust",    "Rowdy",      "Ruddy",
    "Runny",     "Rusty",     "Sandy",     "Scented",    "Scrawny",
    "Secret",    "Serene",    "Shabby",    "Shallow",    "Shameless",
    "Shocking",  "Showy",     "Silky",     "Silver",     "Sinful",
    "Skinny",    "Slimy",     "Snappy",    "Snoopy",     "Solid",
    "Soulful",   "Spanish",   "Spicy",     "Spiteful",   "Spotless",
    "Squeaky",   "Standard",  "Starry",    "Stingy",     "Strident",
    "Stunning",  "Sturdy",    "Sunny",     "Superb",     "Tattered",
    "Tender",    "Thankful",  "Thorny",    "Threadbare", "Timely",
    "Tiny",      "Total",     "Treasured", "Trifling",   "Trusting",
    "Truthful",  "Ugly",      "Unique",    "Unknown",    "Unsung",
    "Untrue",    "Upbeat",    "Upset",     "Useful",     "Utter",
    "Valid",     "Vibrant",   "Vital",     "Warlike",    "Wasteful",
    "Wavy",      "Weary",     "Weepy",     "Welcome",    "Whispered",
    "Wicked",    "Wilted",    "Windy",     "Witty",      "Wooden",
    "Worldly",   "Worthless", "Worthy",    "Writhing",   "Yearly",
    "Youthful"
};

static const char* const g_adjectives2_2[256] = {
    "Aching",     "Adept",      "Advanced",   "Agile",      "Alarmed",
    "Ample",      "Anchored",   "Angry",      "Antique",    "Any",
    "Ashamed",    "Austere",    "Awesome",    "Awkward",    "Basic",
    "Bewitched",  "Blaring",    "Blushing",   "Boiling",    "Boring",
    "Bouncy",     "Broken",     "Bulky",      "Burly",      "Buzzing",
    "Canine",     "Careful",    "Charming",   "Cheery",     "Classic",
    "Cloudy",     "Clumsy",     "Common",     "Complex",    "Concrete",
    "Content",    "Corrupt",    "Creamy",     "Crooked",    "Cruel",
    "Cuddly",     "Curvy",      "Dapper",     "Deadly",     "Decent",
    "Dental",     "Dimpled",    "Dirty",      "Disguised",  "Distant",
    "Dopey",      "Double",     "Downright",  "Dreary",     "Droopy",
    "Eager",      "Earnest",    "Empty",      "Equal",      "Even",
    "Expert",     "Faithful",   "Fancy",      "Fearful",    "Feisty",
    "Female",     "Filthy",     "Fitting",    "Flashy",     "Flimsy",
    "Fluffy",     "Flustered",  "Foolish",    "Forthright", "Frequent",
    "Frightened", "Frilly",     "Frozen",     "Fruitful",   "Fuzzy",
    "Giant",      "Gifted",     "Glaring",    "Gleeful",    "Glossy",
    "Gorgeous",   "Grateful",   "Grimy",      "Grotesque",  "Grounded",
    "Growling",   "Grumpy",     "Hairy",      "Handy",      "Harmful",
    "Hasty",      "Haunting",   "Heartfelt",  "Heavy",      "Helpful",
    "Hidden",     "Honest",     "Hopeful",    "Humming",    "Hurtful",
    "Icy",        "Idle",       "Inborn",     "Itchy",      "Jaunty",
    "Jolly",      "Joyous",     "Jumbo",      "Junior",     "Knobby",
    "Knowing",    "Kosher",     "Lasting",    "Lawful",     "Leading",
    "Legal",      "Liquid",     "Lively",     "Loathsome",  "Long-term",
    "Loving",     "Lumpy",      "Major",      "Married",    "Meager",
    "Measly",     "Mellow",     "Messy",      "Mindless",   "Modern",
    "Monstrous",  "Moral",      "Muffled",    "Murky",      "Musty",
    "Naive",      "Nasty",      "Needy",      "Nifty",      "Nonstop",
    "Novel",      "Nutty",      "Oblong",     "Oddball",    "Oily",
    "Open",       "Our",        "Paltry",     "Pastel",     "Perfect",
    "Perky",      "Petty",      "Piercing",   "Plastic",    "Pleasant",
    "Pointed",    "Polite",     "Precious",   "Present",    "Pricey",
    "Pristine",   "Proper",     "Pungent",    "Purple",     "Putrid",
    "Queasy",     "Quirky",     "Rapid",      "Recent",     "Regal",
    "Remote",     "Roasted",    "Rosy",       "Royal",      "Rundown",
    "Rural",      "Salty",      "Scary",      "Scratchy",   "Second",
    "Selfish",    "Severe",     "Shady",      "Shameful",   "Shiny",
    "Shoddy",     "Silent",     "Silly",      "Simple",     "Single",
    "Sleepy",     "Smoggy",     "Sneaky",     "Soggy",      "Somber",
    "Sour",       "Sparkling",  "Spiffy",     "Splendid",   "Spotted",
    "Stable",     "Starchy",    "Sticky",     "Stormy",     "Striking",
    "Stupid",     "Sudden",     "Super",      "Sweaty",     "Teeming",
    "Testy",      "Thirsty",    "Thoughtful", "Thrifty",    "Tinted",
    "Tired",      "Tragic",     "Tricky",     "Troubled",   "Trusty",
    "Tubby",      "Unfit",      "Unkempt",    "Unlined",    "Untried",
    "Unused",     "Upright",    "Urban",      "Useless",    "Vacant",
    "Vapid",      "Vicious",    "Vivid",      "Wary",       "Watchful",
    "Wealthy",    "Weekly",     "Weighty",    "Whirlwind",  "Whopping",
    "Willing",    "Winding",    "Wiry",       "Woeful",     "Woozy",
    "Worried",    "Worthwhile", "Wretched",   "Yawning",    "Yellow",
    "Yummy"
};

static const char* const g_adjectives3[256] = {
    "Abandoned",    "Absolute",    "Accomplished", "Accurate",    "Acidic",
    "Actual",       "Admired",     "Aggressive",   "Alarming",    "Amazing",
    "Ambitious",    "Amusing",     "Angelic",      "Another",     "Athletic",
    "Attentive",    "Attractive",  "Authentic",    "Authorized",  "Average",
    "Babyish",      "Beautiful",   "Belated",      "Bountiful",   "Burdensome",
    "Bustling",     "Buttery",     "Capital",      "Circular",    "Colorful",
    "Colorless",    "Colossal",    "Competent",    "Courageous",  "Courteous",
    "Creative",     "Criminal",    "Critical",     "Cumbersome",  "Decimal",
    "Defensive",    "Defiant",     "Definite",     "Delicious",   "Delightful",
    "Dependent",    "Descriptive", "Deserted",     "Determined",  "Devoted",
    "Different",    "Difficult",   "Digital",      "Disastrous",  "Disgusting",
    "Dishonest",    "Distorted",   "Dramatic",     "Dutiful",     "Ecstatic",
    "Edible",       "Elaborate",   "Elastic",      "Elated",      "Elderly",
    "Electric",     "Elegant",     "Embarrassed",  "Eminent",     "Enchanted",
    "Enchanting",   "Enlightened", "Enormous",     "Entire",      "Envious",
    "Essential",    "Ethical",     "Evergreen",    "Every",       "Exalted",
    "Excellent",    "Exciting",    "Exhausted",    "Exotic",      "Faraway",
    "Fatherly",     "Favorite",    "Flamboyant",   "Flickering",  "Foolhardy",
    "Fortunate",    "Frightening", "Frivolous",    "Fumbling",    "Functional",
    "Gaseous",      "General",     "Generous",     "Genuine",     "Gigantic",
    "Glamorous",    "Glistening",  "Glittering",   "Glorious",    "Grandiose",
    "Granular",     "Gullible",    "Hideous",      "Horrible",    "Ignorant",
    "Illegal",      "Impartial",   "Impassioned",  "Imperfect",   "Important",
    "Incomplete",   "Indolent",    "Infamous",     "Infantile",   "Infinite",
    "Innocent",     "Insecure",    "Insistent",    "Instructive", "Internal",
    "Ironclad",     "Jovial",      "Jubilant",     "Judicious",   "Juvenile",
    "Lighthearted", "Likable",     "Lopsided",     "Lovable",     "Lumbering",
    "Luminous",     "Majestic",    "Medical",      "Medium",      "Melodic",
    "Menacing",     "Metallic",    "Misguided",    "Mortified",   "Motherly",
    "Motionless",   "Mountainous", "Nautical",     "Negative",    "Neglected",
    "Neighboring",  "Nocturnal",   "Notable",      "Noteworthy",  "Nutritious",
    "Offensive",    "Official",    "Optimal",      "Opulent",     "Orderly",
    "Organic",      "Outgoing",    "Outlandish",   "Outlying",    "Outrageous",
    "Outstanding",  "Overdue",     "Overjoyed",    "Overlooked",  "Parallel",
    "Personal",     "Pertinent",   "Physical",     "Popular",     "Positive",
    "Possible",     "Potable",     "Powerless",    "Practical",   "Prestigious",
    "Previous",     "Probable",    "Punctual",     "Qualified",   "Quarrelsome",
    "Quarterly",    "Querulous",   "Quixotic",     "Radiant",     "Regular",
    "Remorseful",   "Repentant",   "Repulsive",    "Required",    "Respectful",
    "Rewarding",    "Sarcastic",   "Sardonic",     "Separate",    "Serious",
    "Serpentine",   "Shadowy",     "Shimmering",   "Skeletal",    "Sociable",
    "Sorrowful",    "Specific",    "Spirited",     "Submissive",  "Substantial",
    "Suburban",     "Sugary",      "Suspicious",   "Sweltering",  "Talkative",
    "Tangible",     "Tedious",     "Terrible",     "Terrific",    "Thunderous",
    "Tremendous",   "Tremendous",  "Trivial",      "Trustworthy", "Unaware",
    "Uncommon",     "Unconscious", "Unequaled",    "Unfinished",  "Unhappy",
    "Unhealthy",    "Uniform",     "United",       "Unlucky",     "Unpleasant",
    "Unsightly",    "Unsteady",    "Untidy",       "Unwilling",   "Unwritten",
    "Usable",       "Valuable",    "Velvety",      "Vigorous",    "Villainous",
    "Virtual",      "Virtuous",    "Visible",      "Vivacious",   "Waterlogged",
    "Whimsical",    "Wiggly",      "Wobbly",       "Wonderful",   "Worrisome",
    "Yellowish"
};

static const char* const g_nouns1[256] = {
    "Arm",     "Art",    "Bank",   "Base",   "Bed",    "Bell",    "Bench",
    "Big",     "Bike",   "Bird",   "Birth",  "Bite",   "Blank",   "Blind",
    "Blue",    "Box",    "Boy",    "Brain",  "Branch", "Brave",   "Breast",
    "Breath",  "Broad",  "Brush",  "Bunch",  "Burn",   "Cake",    "Cap",
    "Car",     "Card",   "Case",   "Cash",   "Chain",  "Chair",   "Chance",
    "Chart",   "Check",  "Cheek",  "Chest",  "Chip",   "Clothes", "Cloud",
    "Club",    "Coat",   "Code",   "Cost",   "Count",  "Court",   "Crash",
    "Cream",   "Cross",  "Dad",    "Dare",   "Death",  "Debt",    "Desk",
    "Dish",    "Disk",   "Dog",    "Drawer", "Dream",  "Dress",   "Drink",
    "Earth",   "Eat",    "Fact",   "Fail",   "Fat",    "Fault",   "Feed",
    "Few",     "Fix",    "Floor",  "Flow",   "Food",   "Foot",    "Force",
    "Form",    "Frame",  "Gap",    "Gear",   "Gene",   "Go",      "Golf",
    "Good",    "Grand",  "Great",  "Green",  "Growth", "Guard",   "Guess",
    "Guy",     "Hall",   "Hand",   "Harm",   "Head",   "Hell",    "Hole",
    "Host",    "Hunt",   "Hurt",   "If",     "Join",   "Judge",   "Jump",
    "Key",     "Kind",   "King",   "Kiss",   "Lake",   "Lead",    "Leg",
    "Lie",     "Life",   "Link",   "List",   "Loan",   "Look",    "Love",
    "Low",     "Main",   "Make",   "Male",   "Mall",   "Match",   "Meet",
    "Mess",    "Might",  "Mine",   "Month",  "Mouse",  "Nail",    "Name",
    "Neck",    "News",   "Noise",  "Nose",   "Note",   "One",     "Page",
    "Pain",    "Pair",   "Past",   "Peace",  "Pen",    "Phase",   "Phone",
    "Phrase",  "Pick",   "Plan",   "Post",   "Pot",    "Pound",   "Pride",
    "Print",   "Prize",  "Prompt", "Proof",  "Pull",   "Punch",   "Quit",
    "Quote",   "Race",   "Range",  "Rate",   "Red",    "Rent",    "Risk",
    "Road",    "Roll",   "Rope",   "Round",  "Rush",   "Sail",    "School",
    "Scratch", "Script", "Seat",   "Sell",   "Shape",  "Share",   "Shift",
    "Ship",    "Shirt",  "Shock",  "Shoe",   "Shoot",  "Shop",    "Show",
    "Sign",    "Sing",   "Sir",    "Size",   "Skill",  "Skirt",   "Sky",
    "Slip",    "Soil",   "Sound",  "Spite",  "Split",  "Sport",   "Spray",
    "Square",  "Stand",  "Star",   "Steak",  "Step",   "Stick",   "Still",
    "Store",   "Strain", "Street", "Stuff",  "Suck",   "Swim",    "Switch",
    "Talk",    "Task",   "Tea",    "Teach",  "Test",   "Theme",   "Thought",
    "Toe",     "Tongue", "Tooth",  "Tough",  "Tour",   "Track",   "Trash",
    "Tree",    "Trip",   "Truck",  "Trust",  "Truth",  "Tune",    "Turn",
    "Two",     "Type",   "Vast",   "View",   "Way",    "Web",     "Week",
    "Weird",   "Wheel",  "White",  "Wife",   "Wind",   "Wish",    "Word",
    "Yard",    "Year",   "Young",  "Zone"
};

static const char* const g_nouns2[256] = {
    "Abuse",     "Active",     "Advance",    "Advice",   "Affair",
    "Affect",    "Airline",    "Anger",      "Apple",    "Army",
    "Aspect",    "Attack",     "Attempt",    "Author",   "Award",
    "Baby",      "Background", "Baseball",   "Basis",    "Being",
    "Birthday",  "Bitter",     "Bother",     "Bottle",   "Boyfriend",
    "Breakfast", "Brilliant",  "Brother",    "Budget",   "Building",
    "Cable",     "Cancel",     "Cancer",     "Carry",    "Channel",
    "Chapter",   "Chicken",    "Classic",    "Climate",  "Closet",
    "Coffee",    "College",    "Complaint",  "Concept",  "Concern",
    "Constant",  "Contact",    "Context",    "Contract", "Control",
    "Cookie",    "Copy",       "Corner",     "County",   "Couple",
    "Courage",   "Cover",      "Crazy",      "Credit",   "Culture",
    "Current",   "Cycle",      "Daughter",   "Dealer",   "Degree",
    "Demand",    "Design",     "Detail",     "Devil",    "Diamond",
    "Diet",      "Dinner",     "Discount",   "Disease",  "Display",
    "Distance",  "District",   "Divide",     "Drama",    "Drawing",
    "Duty",      "Engine",     "Equal",      "Evening",  "Event",
    "Exam",      "Exchange",   "Extreme",    "Factor",   "Failure",
    "Feature",   "Female",     "Finding",    "Finger",   "Finish",
    "Focus",     "Formal",     "Friendship", "Garage",   "Gather",
    "Guidance",  "Heavy",      "Hello",      "Hire",     "Homework",
    "Hour",      "Human",      "Hurry",      "Image",    "Impress",
    "Income",    "Inside",     "Instance",   "Judgment", "Junior",
    "Jury",      "Knowledge",  "Ladder",     "Language", "Layer",
    "Leader",    "Leading",    "Leather",    "Lesson",   "Letter",
    "Living",    "Local",      "Market",     "Master",   "Meeting",
    "Mention",   "Menu",       "Method",     "Minor",    "Mirror",
    "Mixture",   "Mobile",     "Morning",    "Mortgage", "Mother",
    "Motor",     "Mountain",   "Muscle",     "Music",    "Nasty",
    "Native",    "Nature",     "Normal",     "Nothing",  "Novel",
    "Number",    "Object",     "Offer",      "Orange",   "Order",
    "Other",     "Outcome",    "Outside",    "Oven",     "Painting",
    "Panic",     "Paper",      "Parking",    "Party",    "Patient",
    "Payment",   "Pension",    "Permit",     "Person",   "Photo",
    "Picture",   "Plastic",    "Poem",       "Present",  "Pressure",
    "Prior",     "Private",    "Problem",    "Produce",  "Product",
    "Promise",   "Public",     "Purchase",   "Quiet",    "Reading",
    "Release",   "Remote",     "Repeat",     "Report",   "Resolve",
    "Resort",    "Resource",   "Respond",    "Reveal",   "Review",
    "River",     "Routine",    "Royal",      "Safety",   "Salad",
    "Sandwich",  "Schedule",   "Science",    "Sector",   "Senior",
    "Series",    "Service",    "Session",    "Shoulder", "Shower",
    "Simple",    "Single",     "Sister",     "Solid",    "Speaker",
    "Spirit",    "Stable",     "Standard",   "Station",  "Status",
    "Stomach",   "Structure",  "Stupid",     "Subject",  "Success",
    "Support",   "Surprise",   "Surround",   "System",   "Tackle",
    "Target",    "Tennis",     "Theory",     "Ticket",   "Title",
    "Today",     "Total",      "Tourist",    "Tower",    "Trainer",
    "Trouble",   "Uncle",      "Unique",     "Unit",     "Upper",
    "Value",     "Village",    "Virus",      "Visit",    "Welcome",
    "Western",   "Winner",     "Winter",     "Witness",  "Wonder",
    "Writer"
};

static const char* const g_verbs2_simple[256] = {
    "Actions",   "Adults",     "Affects",    "Airports",    "Alarms",
    "Amounts",   "Angers",     "Apples",     "Assists",     "Attempts",
    "Authors",   "Awards",     "Babies",     "Backgrounds", "Baskets",
    "Battles",   "Beaches",    "Bedrooms",   "Begins",      "Benches",
    "Birthdays", "Bitters",    "Bodies",     "Borders",     "Bosses",
    "Boxes",     "Branches",   "Bridges",    "Brushes",     "Budgets",
    "Bunches",   "Busses",     "Buttons",    "Buyers",      "Candies",
    "Catches",   "Causes",     "Chickens",   "Chocolates",  "Choices",
    "Closets",   "Collars",    "Comforts",   "Commands",    "Comments",
    "Commons",   "Complaints", "Conflicts",  "Contexts",    "Controls",
    "Converts",  "Cookies",    "Copies",     "Corners",     "Counties",
    "Courses",   "Covers",     "Crashes",    "Credits",     "Currents",
    "Cycles",    "Dances",     "Datas",      "Degrees",     "Designs",
    "Details",   "Diets",      "Doctors",    "Doubles",     "Eases",
    "Efforts",   "Employs",    "Engines",    "Entries",     "Essays",
    "Estates",   "Evens",      "Failures",   "Farmers",     "Fathers",
    "Females",   "Figures",    "Finals",     "Fingers",     "Fishes",
    "Flowers",   "Follows",    "Forces",     "Fortunes",    "Freedoms",
    "Gardens",   "Gathers",    "Glasses",    "Guesses",     "Habits",
    "Handles",   "Heavies",    "Highlights", "Hires",       "Horses",
    "Hotels",    "Houses",     "Hurries",    "Husbands",    "Ices",
    "Impacts",   "Insects",    "Insides",    "Invites",     "Irons",
    "Islands",   "Items",      "Jackets",    "Juries",      "Kisses",
    "Ladders",   "Ladies",     "Landscapes", "Leaders",     "Leathers",
    "Lectures",  "Levels",     "Locals",     "Lunches",     "Majors",
    "Manners",   "Marches",    "Matches",    "Matters",     "Members",
    "Mentions",  "Messes",     "Mirrors",    "Misses",      "Mistakes",
    "Mobiles",   "Moments",    "Moneys",     "Motors",      "Networks",
    "Noises",    "Novels",     "Options",    "Others",      "Outsides",
    "Ovens",     "Owners",     "Parties",    "Passes",      "Passions",
    "Patients",  "Payments",   "Pensions",   "Persons",     "Photos",
    "Pieces",    "Pitches",    "Pizzas",     "Presents",    "Prices",
    "Priors",    "Privates",   "Products",   "Profiles",    "Profits",
    "Programs",  "Projects",   "Purples",    "Pushes",      "Questions",
    "Races",     "Ranges",     "Reaches",    "Reasons",     "Records",
    "Regrets",   "Reliefs",    "Repairs",    "Repeats",     "Reports",
    "Requests",  "Reserves",   "Resists",    "Resolves",    "Reviews",
    "Riches",    "Rivers",     "Routines",   "Royals",      "Rushes",
    "Salads",    "Samples",    "Savings",    "Searches",    "Seasons",
    "Seconds",   "Sectors",    "Senses",     "Series",      "Shelters",
    "Shoulders", "Showers",    "Silvers",    "Singles",     "Sizes",
    "Solids",    "Somewheres", "Sources",    "Spaces",      "Spirits",
    "Stables",   "Stages",     "Standards",  "Statements",  "Strangers",
    "Stresses",  "Stretches",  "Struggles",  "Students",    "Studies",
    "Summers",   "Supports",   "Surrounds",  "Surveys",     "Systems",
    "Tables",    "Targets",    "Taxes",      "Teachers",    "Teaches",
    "Tennis",    "Tensions",   "Todays",     "Totals",      "Touches",
    "Tourists",  "Towels",     "Towers",     "Travels",     "Unions",
    "Units",     "Uppers",     "Upstairs",   "Uses",        "Values",
    "Virus",     "Visits",     "Visuals",    "Watches",     "Weakness",
    "Welcomes",  "Westerns",   "Windows",    "Winters",     "Wishes",
    "Workers"
};

static const char* const g_verbs2_progressive[256] = {
    "Aging",     "Airing",    "Arming",    "Asking",     "Backing",
    "Baking",    "Balling",   "Banding",   "Banking",    "Banking",
    "Bathing",   "Beaching",  "Bearing",   "Being",      "Belling",
    "Bending",   "Biking",    "Billing",   "Birthing",   "Bitting",
    "Blanking",  "Boning",    "Booting",   "Bowling",    "Branching",
    "Braving",   "Breasting", "Bridging",  "Browning",   "Bugging",
    "Buying",    "Calming",   "Camping",   "Canning",    "Casing",
    "Catching",  "Causing",   "Changing",  "Charging",   "Charting",
    "Chipping",  "Clubbing",  "Coaching",  "Coasting",   "Cooking",
    "Costing",   "Coupling",  "Coursing",  "Courting",   "Cowing",
    "Crashing",  "Crying",    "Cutting",   "Dancing",    "Dealing",
    "Dotting",   "Dragging",  "Dreaming",  "Dressing",   "Drinking",
    "Dropping",  "Dumping",   "Eating",    "Edging",     "Failing",
    "Fanning",   "Farming",   "Faulting",  "Feeling",    "Filing",
    "Fishing",   "Fixing",    "Flooring",  "Folding",    "Fuelling",
    "Gaining",   "Gifting",   "Going",     "Golding",    "Golfing",
    "Gooding",   "Grabbing",  "Greening",  "Grinding",   "Guessing",
    "Handling",  "Hating",    "Heading",   "Helling",    "Helping",
    "Hiding",    "Hiring",    "Homing",    "Hoping",     "Horsing",
    "Housing",   "Hunting",   "Joining",   "Joking",     "Judging",
    "Kidding",   "Killing",   "Kissing",   "Kneeing",    "Lacking",
    "Landing",   "Leading",   "Leading",   "Leaving",    "Legging",
    "Letting",   "Lighting",  "Listing",   "Loading",    "Loaning",
    "Locking",   "Looking",   "Lowing",    "Lucking",    "Lying",
    "Making",    "Manning",   "Mapping",   "Marching",   "Matching",
    "Mealing",   "Meeting",   "Minding",   "Morning",    "Moving",
    "Netting",   "Noting",    "Nursing",   "Oiling",     "Pacing",
    "Packing",   "Paging",    "Painting",  "Pairing",    "Parking",
    "Passing",   "Pasting",   "Pausing",   "Peaking",    "Phrasing",
    "Picking",   "Piping",    "Planning",  "Pointing",   "Pounding",
    "Prompting", "Pulling",   "Pushing",   "Quitting",   "Raising",
    "Ranging",   "Reading",   "Reading",   "Redding",    "Resting",
    "Riding",    "Ringing",   "Ripping",   "Rising",     "Risking",
    "Roling",    "Roofing",   "Rooming",   "Roughing",   "Rounding",
    "Rowing",    "Rubbing",   "Ruling",    "Running",    "Sailing",
    "Saling",    "Sampling",  "Scaling",   "Scoring",    "Searching",
    "Seating",   "Shifting",  "Shining",   "Shipping",   "Shocking",
    "Shooting",  "Showing",   "Signing",   "Singing",    "Sizing",
    "Skilling",  "Sleeping",  "Sliding",   "Slipping",   "Smelling",
    "Smiling",   "Snowing",   "Sourcing",  "Spacing",    "Sparing",
    "Speeding",  "Spelling",  "Splitting", "Sporting",   "Spotting",
    "Spreading", "Springing", "Staffing",  "Stating",    "Staying",
    "Stealing",  "Stepping",  "Stocking",  "Stopping",   "Storing",
    "Storming",  "Straining", "Stressing", "Stretching", "Striking",
    "Stripping", "Stroking",  "Swimming",  "Swimming",   "Tackling",
    "Talking",   "Tanking",   "Tasting",   "Taxing",     "Testing",
    "Thanking",  "Thinking",  "Timing",    "Tracking",   "Trading",
    "Tripping",  "Trucking",  "Trusting",  "Trying",     "Tuning",
    "Typing",    "Waking",    "Warning",   "Washing",    "Wearing",
    "Webbing",   "Weighting", "Wheeling",  "Willing",    "Winging",
    "Wining",    "Wishing",   "Working",   "Worthing",   "Wrapping",
    "Writing"
};

static size_t write_c_str(char **pbuf,
                          size_t *pbuf_size,
                          const char *str) {
    return __evil_write_literal(pbuf, pbuf_size, str, strlen(str));
}

size_t __evil_write_haiku_for_ptr(char **pbuf,
                                  size_t *pbuf_size,
                                  const void *ptr)
{
    assert(sizeof(unsigned long long) >= sizeof(ptr));
    unsigned long long num_val = (unsigned long long)ptr;
    uint_least8_t parts[] = {
        (uint_least8_t)((num_val & 0xFF00000000000000) >> 56),
        (uint_least8_t)((num_val & 0x00FF000000000000) >> 48),
        (uint_least8_t)((num_val & 0x0000FF0000000000) >> 40),
        (uint_least8_t)((num_val & 0x000000FF00000000) >> 32),
        (uint_least8_t)((num_val & 0x00000000FF000000) >> 24),
        (uint_least8_t)((num_val & 0x0000000000FF0000) >> 16),
        (uint_least8_t)((num_val & 0x000000000000FF00) >> 8),
        (uint_least8_t)((num_val & 0x00000000000000FF) >> 0),
    };

    return write_c_str(pbuf, pbuf_size, g_adjectives3[parts[0]])
        + write_c_str(pbuf, pbuf_size, g_nouns2[parts[1]])
        + write_c_str(pbuf, pbuf_size, g_adjectives2_1[parts[2]])
        + write_c_str(pbuf, pbuf_size, g_adjectives2_2[parts[3]])
        + write_c_str(pbuf, pbuf_size, g_nouns1[parts[4]])
        + write_c_str(pbuf, pbuf_size, g_verbs2_simple[parts[5]])
        + write_c_str(pbuf, pbuf_size, g_verbs2_progressive[parts[6]])
        + write_c_str(pbuf, pbuf_size, "The")
        + write_c_str(pbuf, pbuf_size, g_nouns2[parts[7]]);
}
