#include <evil-config.h>

#include "utils.h"

#include "string.h"
#include "stdint.h"
#include "assert.h"

size_t __evil_write_literal(char *restrict *pbuf,
                            size_t *pbuf_size,
                            const char *str,
                            size_t str_size)
{
    size_t bytes_to_copy = str_size < *pbuf_size ? str_size : *pbuf_size;
    memcpy(*pbuf, str, bytes_to_copy);
    *pbuf += bytes_to_copy;
    *pbuf_size -= bytes_to_copy;
    return str_size;
}

static const char* const g_adjectives2_1[256] = {
    "Able",      "Active",    "Adored",    "Afraid",     "Ajar",
    "Alive",     "Amused",    "Ancient",   "Anguished",  "Anxious",
    "Arctic",    "Assured",   "Aware",     "Awful",      "Barren",
    "Beloved",   "Bitter",    "Blissful",  "Bogus",      "Bony",
    "Bossy",     "Brilliant", "Bubbly",    "Buoyant",    "Busy",
    "Candid",    "Carefree",  "Cautious",  "Cheerful",   "Chilly",
    "Clever",    "Clueless",  "Cluttered", "Complete",   "Composed",
    "Conscious", "Corny",     "Crafty",    "Creepy",     "Crowded",
    "Crushing",  "Cultured",  "Damaged",   "Daring",     "Dearest",
    "Delayed",   "Detailed",  "Direct",    "Discrete",   "Dismal",
    "Distant",   "Doting",    "Downright", "Drafty",     "Dreary",
    "Dual",      "Early",     "Easy",      "Enraged",    "Esteemed",
    "Evil",      "Failing",   "Famous",    "Fatal",      "Fearless",
    "Feline",    "Fickle",    "Finished",  "Flaky",      "Flawless",
    "Flippant",  "Fluid",     "Focused",   "Formal",     "Fragrant",
    "Friendly",  "Frigid",    "Frosty",    "Frugal",     "Fussy",
    "Gentle",    "Giddy",     "Giving",    "Gleaming",   "Gloomy",
    "Golden",    "Graceful",  "Greedy",    "Gripping",   "Grouchy",
    "Growing",   "Grubby",    "Guilty",    "Handsome",   "Happy",
    "Harmless",  "Hateful",   "Healthy",   "Hearty",     "Hefty",
    "Helpless",  "Homely",    "Honored",   "Humble",     "Hungry",
    "Husky",     "Ideal",     "Immense",   "Intent",     "Jaded",
    "Jealous",   "Joyful",    "Juicy",     "Jumpy",      "Kindly",
    "Knotty",    "Kooky",     "Lanky",     "Lavish",     "Lazy",
    "Leafy",     "Limping",   "Little",    "Livid",      "Lonely",
    "Lovely",    "Loyal",     "Lustrous",  "Mammoth",    "Massive",
    "Mealy",     "Meaty",     "Merry",     "Milky",      "Minor",
    "Modest",    "Monthly",   "Muddy",     "Mundane",    "Mushy",
    "Muted",     "Narrow",    "Naughty",   "Nervous",    "Nippy",
    "Normal",    "Noxious",   "Obese",     "Oblong",     "Offbeat",
    "Only",      "Other",     "Oval",      "Partial",    "Peaceful",
    "Perfumed",  "Pesky",     "Phony",     "Plaintive",  "Playful",
    "Pleasing",  "Pointless", "Portly",    "Precious",   "Pretty",
    "Prickly",   "Profuse",   "Prudent",   "Puny",       "Pushy",
    "Puzzled",   "Quiet",     "Ragged",    "Ready",      "Reckless",
    "Relieved",  "Rigid",     "Robust",    "Rowdy",      "Ruddy",
    "Runny",     "Rusty",     "Sandy",     "Scented",    "Scrawny",
    "Secret",    "Serene",    "Shabby",    "Shallow",    "Shameless",
    "Shocking",  "Showy",     "Silky",     "Silver",     "Sinful",
    "Skinny",    "Slimy",     "Snappy",    "Snoopy",     "Solid",
    "Soulful",   "Spanish",   "Spicy",     "Spiteful",   "Spotless",
    "Squeaky",   "Standard",  "Starry",    "Stingy",     "Strident",
    "Stunning",  "Sturdy",    "Sunny",     "Superb",     "Tattered",
    "Tender",    "Thankful",  "Thorny",    "Threadbare", "Timely",
    "Tiny",      "Total",     "Treasured", "Trifling",   "Trusting",
    "Truthful",  "Ugly",      "Unique",    "Unknown",    "Unsung",
    "Untrue",    "Upbeat",    "Upset",     "Useful",     "Utter",
    "Valid",     "Vibrant",   "Vital",     "Warlike",    "Wasteful",
    "Wavy",      "Weary",     "Weepy",     "Welcome",    "Whispered",
    "Wicked",    "Wilted",    "Windy",     "Witty",      "Wooden",
    "Worldly",   "Worthless", "Worthy",    "Writhing",   "Yearly",
    "Youthful"
};

static const char* const g_adjectives2_2[256] = {
    "Aching",     "Adept",      "Advanced",   "Agile",      "Alarmed",
    "Ample",      "Anchored",   "Angry",      "Antique",    "Any",
    "Ashamed",    "Austere",    "Awesome",    "Awkward",    "Basic",
    "Bewitched",  "Blaring",    "Blushing",   "Boiling",    "Boring",
    "Bouncy",     "Broken",     "Bulky",      "Burly",      "Buzzing",
    "Canine",     "Careful",    "Charming",   "Cheery",     "Classic",
    "Cloudy",     "Clumsy",     "Common",     "Complex",    "Concrete",
    "Content",    "Corrupt",    "Creamy",     "Crooked",    "Cruel",
    "Cuddly",     "Curvy",      "Dapper",     "Deadly",     "Decent",
    "Dental",     "Dimpled",    "Dirty",      "Disguised",  "Distant",
    "Dopey",      "Double",     "Downright",  "Dreary",     "Droopy",
    "Eager",      "Earnest",    "Empty",      "Equal",      "Even",
    "Expert",     "Faithful",   "Fancy",      "Fearful",    "Feisty",
    "Female",     "Filthy",     "Fitting",    "Flashy",     "Flimsy",
    "Fluffy",     "Flustered",  "Foolish",    "Forthright", "Frequent",
    "Frightened", "Frilly",     "Frozen",     "Fruitful",   "Fuzzy",
    "Giant",      "Gifted",     "Glaring",    "Gleeful",    "Glossy",
    "Gorgeous",   "Grateful",   "Grimy",      "Grotesque",  "Grounded",
    "Growling",   "Grumpy",     "Hairy",      "Handy",      "Harmful",
    "Hasty",      "Haunting",   "Heartfelt",  "Heavy",      "Helpful",
    "Hidden",     "Honest",     "Hopeful",    "Humming",    "Hurtful",
    "Icy",        "Idle",       "Inborn",     "Itchy",      "Jaunty",
    "Jolly",      "Joyous",     "Jumbo",      "Junior",     "Knobby",
    "Knowing",    "Kosher",     "Lasting",    "Lawful",     "Leading",
    "Legal",      "Liquid",     "Lively",     "Loathsome",  "Long-term",
    "Loving",     "Lumpy",      "Major",      "Married",    "Meager",
    "Measly",     "Mellow",     "Messy",      "Mindless",   "Modern",
    "Monstrous",  "Moral",      "Muffled",    "Murky",      "Musty",
    "Naive",      "Nasty",      "Needy",      "Nifty",      "Nonstop",
    "Novel",      "Nutty",      "Oblong",     "Oddball",    "Oily",
    "Open",       "Our",        "Paltry",     "Pastel",     "Perfect",
    "Perky",      "Petty",      "Piercing",   "Plastic",    "Pleasant",
    "Pointed",    "Polite",     "Precious",   "Present",    "Pricey",
    "Pristine",   "Proper",     "Pungent",    "Purple",     "Putrid",
    "Queasy",     "Quirky",     "Rapid",      "Recent",     "Regal",
    "Remote",     "Roasted",    "Rosy",       "Royal",      "Rundown",
    "Rural",      "Salty",      "Scary",      "Scratchy",   "Second",
    "Selfish",    "Severe",     "Shady",      "Shameful",   "Shiny",
    "Shoddy",     "Silent",     "Silly",      "Simple",     "Single",
    "Sleepy",     "Smoggy",     "Sneaky",     "Soggy",      "Somber",
    "Sour",       "Sparkling",  "Spiffy",     "Splendid",   "Spotted",
    "Stable",     "Starchy",    "Sticky",     "Stormy",     "Striking",
    "Stupid",     "Sudden",     "Super",      "Sweaty",     "Teeming",
    "Testy",      "Thirsty",    "Thoughtful", "Thrifty",    "Tinted",
    "Tired",      "Tragic",     "Tricky",     "Troubled",   "Trusty",
    "Tubby",      "Unfit",      "Unkempt",    "Unlined",    "Untried",
    "Unused",     "Upright",    "Urban",      "Useless",    "Vacant",
    "Vapid",      "Vicious",    "Vivid",      "Wary",       "Watchful",
    "Wealthy",    "Weekly",     "Weighty",    "Whirlwind",  "Whopping",
    "Willing",    "Winding",    "Wiry",       "Woeful",     "Woozy",
    "Worried",    "Worthwhile", "Wretched",   "Yawning",    "Yellow",
    "Yummy"
};

static const char* const g_adjectives3[256] = {
    "Abandoned",    "Absolute",    "Accomplished", "Accurate",    "Acidic",
    "Actual",       "Admired",     "Aggressive",   "Alarming",    "Amazing",
    "Ambitious",    "Amusing",     "Angelic",      "Another",     "Athletic",
    "Attentive",    "Attractive",  "Authentic",    "Authorized",  "Average",
    "Babyish",      "Beautiful",   "Belated",      "Bountiful",   "Burdensome",
    "Bustling",     "Buttery",     "Capital",      "Circular",    "Colorful",
    "Colorless",    "Colossal",    "Competent",    "Courageous",  "Courteous",
    "Creative",     "Criminal",    "Critical",     "Cumbersome",  "Decimal",
    "Defensive",    "Defiant",     "Definite",     "Delicious",   "Delightful",
    "Dependent",    "Descriptive", "Deserted",     "Determined",  "Devoted",
    "Different",    "Difficult",   "Digital",      "Disastrous",  "Disgusting",
    "Dishonest",    "Distorted",   "Dramatic",     "Dutiful",     "Ecstatic",
    "Edible",       "Elaborate",   "Elastic",      "Elated",      "Elderly",
    "Electric",     "Elegant",     "Embarrassed",  "Eminent",     "Enchanted",
    "Enchanting",   "Enlightened", "Enormous",     "Entire",      "Envious",
    "Essential",    "Ethical",     "Evergreen",    "Every",       "Exalted",
    "Excellent",    "Exciting",    "Exhausted",    "Exotic",      "Faraway",
    "Fatherly",     "Favorite",    "Flamboyant",   "Flickering",  "Foolhardy",
    "Fortunate",    "Frightening", "Frivolous",    "Fumbling",    "Functional",
    "Gaseous",      "General",     "Generous",     "Genuine",     "Gigantic",
    "Glamorous",    "Glistening",  "Glittering",   "Glorious",    "Grandiose",
    "Granular",     "Gullible",    "Hideous",      "Horrible",    "Ignorant",
    "Illegal",      "Impartial",   "Impassioned",  "Imperfect",   "Important",
    "Incomplete",   "Indolent",    "Infamous",     "Infantile",   "Infinite",
    "Innocent",     "Insecure",    "Insistent",    "Instructive", "Internal",
    "Ironclad",     "Jovial",      "Jubilant",     "Judicious",   "Juvenile",
    "Lighthearted", "Likable",     "Lopsided",     "Lovable",     "Lumbering",
    "Luminous",     "Majestic",    "Medical",      "Medium",      "Melodic",
    "Menacing",     "Metallic",    "Misguided",    "Mortified",   "Motherly",
    "Motionless",   "Mountainous", "Nautical",     "Negative",    "Neglected",
    "Neighboring",  "Nocturnal",   "Notable",      "Noteworthy",  "Nutritious",
    "Offensive",    "Official",    "Optimal",      "Opulent",     "Orderly",
    "Organic",      "Outgoing",    "Outlandish",   "Outlying",    "Outrageous",
    "Outstanding",  "Overdue",     "Overjoyed",    "Overlooked",  "Parallel",
    "Personal",     "Pertinent",   "Physical",     "Popular",     "Positive",
    "Possible",     "Potable",     "Powerless",    "Practical",   "Prestigious",
    "Previous",     "Probable",    "Punctual",     "Qualified",   "Quarrelsome",
    "Quarterly",    "Querulous",   "Quixotic",     "Radiant",     "Regular",
    "Remorseful",   "Repentant",   "Repulsive",    "Required",    "Respectful",
    "Rewarding",    "Sarcastic",   "Sardonic",     "Separate",    "Serious",
    "Serpentine",   "Shadowy",     "Shimmering",   "Skeletal",    "Sociable",
    "Sorrowful",    "Specific",    "Spirited",     "Submissive",  "Substantial",
    "Suburban",     "Sugary",      "Suspicious",   "Sweltering",  "Talkative",
    "Tangible",     "Tedious",     "Terrible",     "Terrific",    "Thunderous",
    "Tremendous",   "Tremendous",  "Trivial",      "Trustworthy", "Unaware",
    "Uncommon",     "Unconscious", "Unequaled",    "Unfinished",  "Unhappy",
    "Unhealthy",    "Uniform",     "United",       "Unlucky",     "Unpleasant",
    "Unsightly",    "Unsteady",    "Untidy",       "Unwilling",   "Unwritten",
    "Usable",       "Valuable",    "Velvety",      "Vigorous",    "Villainous",
    "Virtual",      "Virtuous",    "Visible",      "Vivacious",   "Waterlogged",
    "Whimsical",    "Wiggly",      "Wobbly",       "Wonderful",   "Worrisome",
    "Yellowish"
};

static const char* const g_nouns1[256] = {
    "Arm",     "Art",    "Bank",   "Base",   "Bed",    "Bell",    "Bench",
    "Big",     "Bike",   "Bird",   "Birth",  "Bite",   "Blank",   "Blind",
    "Blue",    "Box",    "Boy",    "Brain",  "Branch", "Brave",   "Breast",
    "Breath",  "Broad",  "Brush",  "Bunch",  "Burn",   "Cake",    "Cap",
    "Car",     "Card",   "Case",   "Cash",   "Chain",  "Chair",   "Chance",
    "Chart",   "Check",  "Cheek",  "Chest",  "Chip",   "Clothes", "Cloud",
    "Club",    "Coat",   "Code",   "Cost",   "Count",  "Court",   "Crash",
    "Cream",   "Cross",  "Dad",    "Dare",   "Death",  "Debt",    "Desk",
    "Dish",    "Disk",   "Dog",    "Drawer", "Dream",  "Dress",   "Drink",
    "Earth",   "Eat",    "Fact",   "Fail",   "Fat",    "Fault",   "Feed",
    "Few",     "Fix",    "Floor",  "Flow",   "Food",   "Foot",    "Force",
    "Form",    "Frame",  "Gap",    "Gear",   "Gene",   "Go",      "Golf",
    "Good",    "Grand",  "Great",  "Green",  "Growth", "Guard",   "Guess",
    "Guy",     "Hall",   "Hand",   "Harm",   "Head",   "Hell",    "Hole",
    "Host",    "Hunt",   "Hurt",   "If",     "Join",   "Judge",   "Jump",
    "Key",     "Kind",   "King",   "Kiss",   "Lake",   "Lead",    "Leg",
    "Lie",     "Life",   "Link",   "List",   "Loan",   "Look",    "Love",
    "Low",     "Main",   "Make",   "Male",   "Mall",   "Match",   "Meet",
    "Mess",    "Might",  "Mine",   "Month",  "Mouse",  "Nail",    "Name",
    "Neck",    "News",   "Noise",  "Nose",   "Note",   "One",     "Page",
    "Pain",    "Pair",   "Past",   "Peace",  "Pen",    "Phase",   "Phone",
    "Phrase",  "Pick",   "Plan",   "Post",   "Pot",    "Pound",   "Pride",
    "Print",   "Prize",  "Prompt", "Proof",  "Pull",   "Punch",   "Quit",
    "Quote",   "Race",   "Range",  "Rate",   "Red",    "Rent",    "Risk",
    "Road",    "Roll",   "Rope",   "Round",  "Rush",   "Sail",    "School",
    "Scratch", "Script", "Seat",   "Sell",   "Shape",  "Share",   "Shift",
    "Ship",    "Shirt",  "Shock",  "Shoe",   "Shoot",  "Shop",    "Show",
    "Sign",    "Sing",   "Sir",    "Size",   "Skill",  "Skirt",   "Sky",
    "Slip",    "Soil",   "Sound",  "Spite",  "Split",  "Sport",   "Spray",
    "Square",  "Stand",  "Star",   "Steak",  "Step",   "Stick",   "Still",
    "Store",   "Strain", "Street", "Stuff",  "Suck",   "Swim",    "Switch",
    "Talk",    "Task",   "Tea",    "Teach",  "Test",   "Theme",   "Thought",
    "Toe",     "Tongue", "Tooth",  "Tough",  "Tour",   "Track",   "Trash",
    "Tree",    "Trip",   "Truck",  "Trust",  "Truth",  "Tune",    "Turn",
    "Two",     "Type",   "Vast",   "View",   "Way",    "Web",     "Week",
    "Weird",   "Wheel",  "White",  "Wife",   "Wind",   "Wish",    "Word",
    "Yard",    "Year",   "Young",  "Zone"
};

static const char* const g_nouns2[256] = {
    "Abuse",     "Active",     "Advance",    "Advice",   "Affair",
    "Affect",    "Airline",    "Anger",      "Apple",    "Army",
    "Aspect",    "Attack",     "Attempt",    "Author",   "Award",
    "Baby",      "Background", "Baseball",   "Basis",    "Being",
    "Birthday",  "Bitter",     "Bother",     "Bottle",   "Boyfriend",
    "Breakfast", "Brilliant",  "Brother",    "Budget",   "Building",
    "Cable",     "Cancel",     "Cancer",     "Carry",    "Channel",
    "Chapter",   "Chicken",    "Classic",    "Climate",  "Closet",
    "Coffee",    "College",    "Complaint",  "Concept",  "Concern",
    "Constant",  "Contact",    "Context",    "Contract", "Control",
    "Cookie",    "Copy",       "Corner",     "County",   "Couple",
    "Courage",   "Cover",      "Crazy",      "Credit",   "Culture",
    "Current",   "Cycle",      "Daughter",   "Dealer",   "Degree",
    "Demand",    "Design",     "Detail",     "Devil",    "Diamond",
    "Diet",      "Dinner",     "Discount",   "Disease",  "Display",
    "Distance",  "District",   "Divide",     "Drama",    "Drawing",
    "Duty",      "Engine",     "Equal",      "Evening",  "Event",
    "Exam",      "Exchange",   "Extreme",    "Factor",   "Failure",
    "Feature",   "Female",     "Finding",    "Finger",   "Finish",
    "Focus",     "Formal",     "Friendship", "Garage",   "Gather",
    "Guidance",  "Heavy",      "Hello",      "Hire",     "Homework",
    "Hour",      "Human",      "Hurry",      "Image",    "Impress",
    "Income",    "Inside",     "Instance",   "Judgment", "Junior",
    "Jury",      "Knowledge",  "Ladder",     "Language", "Layer",
    "Leader",    "Leading",    "Leather",    "Lesson",   "Letter",
    "Living",    "Local",      "Market",     "Master",   "Meeting",
    "Mention",   "Menu",       "Method",     "Minor",    "Mirror",
    "Mixture",   "Mobile",     "Morning",    "Mortgage", "Mother",
    "Motor",     "Mountain",   "Muscle",     "Music",    "Nasty",
    "Native",    "Nature",     "Normal",     "Nothing",  "Novel",
    "Number",    "Object",     "Offer",      "Orange",   "Order",
    "Other",     "Outcome",    "Outside",    "Oven",     "Painting",
    "Panic",     "Paper",      "Parking",    "Party",    "Patient",
    "Payment",   "Pension",    "Permit",     "Person",   "Photo",
    "Picture",   "Plastic",    "Poem",       "Present",  "Pressure",
    "Prior",     "Private",    "Problem",    "Produce",  "Product",
    "Promise",   "Public",     "Purchase",   "Quiet",    "Reading",
    "Release",   "Remote",     "Repeat",     "Report",   "Resolve",
    "Resort",    "Resource",   "Respond",    "Reveal",   "Review",
    "River",     "Routine",    "Royal",      "Safety",   "Salad",
    "Sandwich",  "Schedule",   "Science",    "Sector",   "Senior",
    "Series",    "Service",    "Session",    "Shoulder", "Shower",
    "Simple",    "Single",     "Sister",     "Solid",    "Speaker",
    "Spirit",    "Stable",     "Standard",   "Station",  "Status",
    "Stomach",   "Structure",  "Stupid",     "Subject",  "Success",
    "Support",   "Surprise",   "Surround",   "System",   "Tackle",
    "Target",    "Tennis",     "Theory",     "Ticket",   "Title",
    "Today",     "Total",      "Tourist",    "Tower",    "Trainer",
    "Trouble",   "Uncle",      "Unique",     "Unit",     "Upper",
    "Value",     "Village",    "Virus",      "Visit",    "Welcome",
    "Western",   "Winner",     "Winter",     "Witness",  "Wonder",
    "Writer"
};

static const char* const g_verbs2_simple[256] = {
    "Accepts",    "Admires",   "Admits",    "Affirms",    "Alerts",
    "Allows",     "Alludes",   "Appeals",   "Appears",    "Argues",
    "Arrests",    "Arrives",   "Asserts",   "Assures",    "Attempts",
    "Attends",    "Attracts",  "Auctions",  "Bargains",   "Battles",
    "Befriends",  "Begins",    "Behaves",   "Believes",   "Bellows",
    "Belongs",    "Bestows",   "Blesses",   "Borrows",    "Branches",
    "Broadcasts", "Brushes",   "Buries",    "Buzzes",     "Carries",
    "Catches",    "Causes",    "Cautions",  "Changes",    "Charges",
    "Chases",     "Chooses",   "Closes",    "Collects",   "Colors",
    "Comforts",   "Commands",  "Competes",  "Complains",  "Concerns",
    "Concludes",  "Concurs",   "Connects",  "Consists",   "Copies",
    "Corrects",   "Counters",  "Covers",    "Covets",     "Crashes",
    "Cycles",     "Dances",    "Debates",   "Decays",     "Declares",
    "Delays",     "Delights",  "Denies",    "Depends",    "Describes",
    "Deserts",    "Deserves",  "Deters",    "Dictates",   "Directs",
    "Dislikes",   "Divides",   "Dresses",   "Echoes",     "Elopes",
    "Emits",      "Employs",   "Enters",    "Escapes",    "Excites",
    "Exhorts",    "Exists",    "Expands",   "Extends",    "Extols",
    "Faces",      "Falters",   "Favors",    "Faxes",      "Fences",
    "Fires",      "Fishes",    "Fixes",     "Flashes",    "Flowers",
    "Gardens",    "Gathers",   "Gazes",     "Grumbles",   "Guesses",
    "Gushes",     "Hammers",   "Happens",   "Highlights", "Hisses",
    "Hovers",     "Hurries",   "Ices",      "Ignores",    "Improves",
    "Includes",   "Infects",   "Inflates",  "Informs",    "Insists",
    "Inspires",   "Instructs", "Invents",   "Invests",    "Invites",
    "Irons",      "Judges",    "Juggles",   "Laments",    "Lectures",
    "Levels",     "Lightens",  "Listens",   "Loosens",    "Loses",
    "Lowers",     "Maintains", "Marches",   "Marries",    "Marvels",
    "Matters",    "Measures",  "Mentions",  "Merges",     "Misses",
    "Mixes",      "Mutters",   "Obeys",     "Objects",    "Observes",
    "Occurs",     "Offends",   "Offers",    "Omits",      "Opens",
    "Paddles",    "Passes",    "Pauses",    "Performs",   "Places",
    "Pleases",    "Preaches",  "Precedes",  "Predicts",   "Prefers",
    "Prepares",   "Presents",  "Preserves", "Presses",    "Proclaims",
    "Programs",   "Protests",  "Provides",  "Punches",    "Punctures",
    "Pushes",     "Questions", "Quizzes",   "Races",      "Raises",
    "Reaches",    "Rebuffs",   "Recites",   "Reflects",   "Rejects",
    "Relates",    "Relies",    "Removes",   "Repairs",    "Replies",
    "Reports",    "Requests",  "Rescues",   "Retorts",    "Returns",
    "Reveals",    "Rises",     "Rushes",    "Savors",     "Scratches",
    "Screeches",  "Searches",  "Senses",    "Severs",     "Shelters",
    "Shivers",    "Signals",   "Slices",    "Smashes",    "Snatches",
    "Sneezes",    "Snickers",  "Sputters",  "Stitches",   "Stresses",
    "Stutters",   "Succeeds",  "Suffers",   "Suggests",   "Supplies",
    "Supports",   "Surrounds", "Suspects",  "Suspends",   "Switches",
    "Teaches",    "Teases",    "Threatens", "Thunders",   "Tickles",
    "Tires",      "Tosses",    "Touches",   "Traces",     "Translates",
    "Transports", "Travels",   "Trickles",  "Troubles",   "Unites",
    "Upsets",     "Urges",     "Uses",      "Usurps",     "Utters",
    "Vacuums",    "Ventures",  "Visits",    "Wanders",    "Watches",
    "Welcomes",   "Whispers",  "Wishes",    "Wonders",    "Worries",
    "Wrestles"
};

static const char* const g_verbs2_progressive[256] = {
    "Aching",    "Acting",    "Adding",    "Ailing",    "Baking",
    "Banging",   "Banning",   "Baring",    "Barking",   "Bearing",
    "Begging",   "Biting",    "Bleaching", "Blessing",  "Blushing",
    "Boiling",   "Bombing",   "Braking",   "Branching", "Bringing",
    "Burning",   "Buying",    "Calling",   "Camping",   "Carving",
    "Catching",  "Changing",  "Chanting",  "Checking",  "Chewing",
    "Chiding",   "Choosing",  "Coming",    "Cooking",   "Costing",
    "Coughing",  "Crashing",  "Croaking",  "Crowding",  "Crushing",
    "Curing",    "Curling",   "Cursing",   "Dancing",   "Digging",
    "Diving",    "Doing",     "Doling",    "Doting",    "Doubting",
    "Draining",  "Drawing",   "Dreaming",  "Dressing",  "Dripping",
    "Droning",   "Dropping",  "Drying",    "Earning",   "Eating",
    "Fading",    "Feeling",   "Filing",    "Filling",   "Filming",
    "Finding",   "Fishing",   "Flooding",  "Flying",    "Fretting",
    "Fuming",    "Gazing",    "Gilding",   "Gnawing",   "Grabbing",
    "Grating",   "Greeting",  "Grinning",  "Grunting",  "Guiding",
    "Hailing",   "Handling",  "Harming",   "Haunting",  "Having",
    "Heading",   "Healing",   "Heaping",   "Hearing",   "Heating",
    "Hiding",    "Hissing",   "Holding",   "Hugging",   "Humming",
    "Jailing",   "Jogging",   "Joking",    "Kicking",   "Kneeling",
    "Knocking",  "Knowing",   "Landing",   "Laughing",  "Laying",
    "Learning",  "Leaving",   "Lending",   "Letting",   "Licking",
    "Lifting",   "Living",    "Longing",   "Lying",     "Mailing",
    "Manning",   "Marking",   "Mating",    "Meeting",   "Mixing",
    "Moaning",   "Mooring",   "Mourning",  "Nagging",   "Napping",
    "Needing",   "Nesting",   "Noting",    "Oiling",    "Owning",
    "Padding",   "Painting",  "Panting",   "Parking",   "Parting",
    "Pasting",   "Pausing",   "Peeling",   "Peering",   "Pinching",
    "Planting",  "Playing",   "Pleading",  "Pledging",  "Plowing",
    "Poking",    "Posting",   "Pouring",   "Praying",   "Preaching",
    "Prying",    "Pulling",   "Punching",  "Putting",   "Quitting",
    "Raining",   "Raining",   "Raving",    "Reading",   "Roaring",
    "Robbing",   "Rubbing",   "Ruling",    "Running",   "Rushing",
    "Sailing",   "Scaring",   "Scorching", "Screaming", "Screeching",
    "Screwing",  "Sealing",   "Searching", "Selling",   "Sending",
    "Sensing",   "Serving",   "Sewing",    "Shaving",   "Shocking",
    "Shooting",  "Shouting",  "Singing",   "Sketching", "Skiing",
    "Sleeping",  "Sliding",   "Slowing",   "Smoking",   "Snapping",
    "Snatching", "Sniffing",  "Soaking",   "Sowing",    "Spanning",
    "Sparing",   "Speaking",  "Spelling",  "Spinning",  "Spraying",
    "Squeezing", "Stabbing",  "Stamping",  "Staring",   "Starring",
    "Stashing",  "Stating",   "Staying",   "Stirring",  "Stitching",
    "Storing",   "Storming",  "Strapping", "Straying",  "Stripping",
    "Stunning",  "Suiting",   "Swaying",   "Switching", "Tapping",
    "Teasing",   "Tempting",  "Testing",   "Thinking",  "Throwing",
    "Timing",    "Tiring",    "Toasting",  "Tossing",   "Touching",
    "Touring",   "Tracing",   "Tracking",  "Trapping",  "Trotting",
    "Trouncing", "Trusting",  "Trying",    "Twisting",  "Using",
    "Voicing",   "Vouching",  "Waking",    "Walking",   "Warming",
    "Wasting",   "Waving",    "Wedding",   "Whining",   "Winking",
    "Wishing",   "Wrestling", "Writing",   "Yawning",   "Yelping",
    "Zipping"
};

static size_t write_c_str(char *restrict *pbuf,
                          size_t *pbuf_size,
                          const char *str) {
    return __evil_write_literal(pbuf, pbuf_size, str, strlen(str));
}

size_t __evil_write_haiku_for_ptr(char *restrict *pbuf,
                                  size_t *pbuf_size,
                                  const void *ptr)
{
    assert(sizeof(unsigned long long) >= sizeof(ptr));
    unsigned long long num_val = (unsigned long long)ptr;
    uint_least8_t parts[] = {
        (uint_least8_t)((num_val & 0xFF00000000000000) >> 56),
        (uint_least8_t)((num_val & 0x00FF000000000000) >> 48),
        (uint_least8_t)((num_val & 0x0000FF0000000000) >> 40),
        (uint_least8_t)((num_val & 0x000000FF00000000) >> 32),
        (uint_least8_t)((num_val & 0x00000000FF000000) >> 24),
        (uint_least8_t)((num_val & 0x0000000000FF0000) >> 16),
        (uint_least8_t)((num_val & 0x000000000000FF00) >> 8),
        (uint_least8_t)((num_val & 0x00000000000000FF) >> 0),
    };

    return write_c_str(pbuf, pbuf_size, g_adjectives3[parts[0]])
        + write_c_str(pbuf, pbuf_size, g_nouns2[parts[1]])
        + write_c_str(pbuf, pbuf_size, g_adjectives2_1[parts[2]])
        + write_c_str(pbuf, pbuf_size, g_adjectives2_2[parts[3]])
        + write_c_str(pbuf, pbuf_size, g_nouns1[parts[4]])
        + write_c_str(pbuf, pbuf_size, g_verbs2_simple[parts[5]])
        + write_c_str(pbuf, pbuf_size, g_verbs2_progressive[parts[6]])
        + write_c_str(pbuf, pbuf_size, "The")
        + write_c_str(pbuf, pbuf_size, g_nouns2[parts[7]]);
}
