#!/bin/bash

set -e

PROJECT_ROOT="$(dirname "$(dirname "$(readlink -f "$0")")")"
BUILD_DIR="$PROJECT_ROOT/build/coverage"
OUTPUT_DIR="$BUILD_DIR/report"
OUTPUT_HTML="$OUTPUT_DIR/coverage.html"


function die() {
    echo -e "$@" >&2
    exit 1
}

which gcovr || die "gcovr not found, exiting"

mkdir -p "$BUILD_DIR"
pushd "$BUILD_DIR"
    cmake -D CMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage -DNDEBUG" \
          -D CMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -DNDEBUG" \
          -D CMAKE_EXE_LINKER_FLAGS="-fprofile-arcs -ftest-coverage" \
          -D CMAKE_BUILD_TYPE=Debug \
          "$PROJECT_ROOT"
    make -j$(nproc) check

    mkdir -p "$OUTPUT_DIR"
    gcovr . --html \
            --html-details \
            --root="$PROJECT_ROOT" \
            --output="$OUTPUT_HTML" \
            --exclude="$PROJECT_ROOT/build" \
            --exclude="$PROJECT_ROOT/test" \
            --exclude="$PROJECT_ROOT/os"
popd

cat <<EOF

-----
Coverage report: $OUTPUT_HTML
EOF

which gio >/dev/null && gio open "$OUTPUT_HTML" \
    || xdg-open "$OUTPUT_HTML"
